config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "charts" => "pages#charts"

  devise_for :users

  resources :users

  resources :users do
    resources :trades
  end

  resources :wallet do
    resources :trades
  end

  resources :users do
    resources :wallets
  end

end

app/models/trade.rb
require 'btce'

class Trade < ActiveRecord::Base
  belongs_to :user
  belongs_to :wallet

  validates :amount, presence: true
  validates :price, presence: true
  validates :user_id, presence: true
  validates :trade_type, presence: true

  def find_price
    ticker = Btce::Ticker.new "btc_usd"
    ticker.avg
  end

  def update_price
    update(price: find_price)
  end

  def calculate_total_usd
    ticker = Btce::Ticker.new "btc_usd"
    if trade_type == "buy"
      amount * ticker.avg * -1
    else
      amount * ticker.avg
    end
  end

  def update_total_usd
    update(total: calculate_total_usd)
  end

  def calculate_total_btc
    if trade_type == "buy"
      amount
    else
      amount * -1
    end
  end

  def update_total_btc
    update(amount: calculate_total_btc)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :initialize_with_wallet

  has_many :trades
  has_one :wallet
  belongs_to :network
  belongs_to :user_leaderboard

  validates :username, presence: true, length: { minimum: 6, maximum: 20 }
  validates :password, presence: true, length: { minimum: 6, maximum: 20 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def default_wallet
    self.wallet
  end

  private

    def initialize_with_wallet
      Wallet.create(user: self)
    end

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  has_many :trades
  belongs_to :user

  def btc_total
    total = 0
    self.trades.each do |trade|
      total += trade.calculate_total_btc
    end
    return total
  end

  def usd_total
    total = 100000
    self.trades.each do |trade|
      total += trade.calculate_total_usd
    end
    return total
  end

  def profits
    profit = 0
    self.trades.each do |trade|
      profit += trade.calculate_total_usd
    end
    return profit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
    devise_parameter_sanitizer.for(:account_update) << [:username]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def charts
    @user = current_user
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def show
    @trade = Trade.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @trade = Trade.new
  endz

  def create
    @trade = current_user.trades.build(trade_params)
    @trade.wallet = current_user.default_wallet
    @trade.update_price
    @trade.update_total_usd
    if @trade.trade_type == "buy" && current_user.wallet.usd_total >= @trade.total && @trade.save
      redirect_to user_path(current_user), notice: "Your transaction was successfully processed."
      @trade.update_price
      @trade.update_total_usd
    elsif @trade.trade_type == "sell" && current_user.wallet.btc_total >= @trade.amount && @trade.save
      redirect_to user_path(current_user), notice: "Your transaction was successfully processed."
      @trade.update_price
      @trade.update_total_usd
    else
      redirect_to user_path(current_user), notice: "We were unable to process your transaction."
    end
  end


  private

    def set_trade
      @trade = Trade.find(params[:id])
    end

    def correct_user
      @trade = current_user.trades.find_by(id: params[:id])
      redirect_to trades_path, notice: "Not authorized to trade." if @trade.nil?
    end

    def trade_params
      params.require(:trade).permit(:price, :amount, :price_currency, :trade_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]

  def show
    @user = current_user
    @wallet = @user.wallet
    @trades = @wallet.trades.order(created_at: :desc).limit(10)
  end

end

app/controllers/who_has_the_most_money_6kyu.rb
class Student
  attr_reader :name
  attr_reader :fives
  attr_reader :tens
  attr_reader :twenties

  def initialize(name, fives, tens, twenties)
    @name = name
    @fives = fives
    @tens = tens
    @twenties = twenties
  end

  def most_money(students)
    students = self.all
    students.each do |student|
      total = student.fives * 5 + student.tens * 10 + student.twenties * 20
      if
      return student.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer navbar-fixed-bottom">
  <div class="container">
    <ul class="nav navbar-nav" float:none>
      <center>
      <li> Created by Adam Andrewjeski,
       Copyright © 2014 Arcade //
       <a href="http://adamandrewjeski.herokuapp.com" target="_blank">About Me</a></li>
      </center>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Arcade</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Charts", charts_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Account Console", user_path(@user) %></li>
        <li><%= link_to "Trade", new_user_trade_path(@user) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to 'Register', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arcade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
         <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/charts.html.erb
<div align="center"><iframe width="750" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://myip.ms/crypto.php?m=7777"></iframe><a href="http://myip.ms/"></a></div>
<br>
<div align="center"><iframe width="750" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://myip.ms/crypto.php?m=3&&c=da4139&t=usd"></iframe><a href="http://myip.ms/"></a></div>
<br>
<div align="center"><iframe width="750" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://myip.ms/crypto.php?m=159&&c=00d313&t=usd"></iframe><a href="http://myip.ms/"></a></div>

app/views/pages/home.html.erb
<center><h1>Welcome to Arcade!</h1></center>

<center>
<p>
<% if user_signed_in? %>
  <%= link_to 'Account Console', user_path(@user) %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>
</p>

</center>

app/views/trades/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h3>Make a Trade</h3>
      <%= form_for [@user, @trade] do |f| %>

        <p>USD/BTC: <%= @trade.find_price %></p>

        <div>
          <%= f.label :amount %>
          <%= f.text_field :amount %>
        </div>

        <div>
          <%= f.label :trade_type %>
          <%= f.select(:trade_type, ['buy', 'sell']) %>
        </div>

        <%= f.submit 'Submit' %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Console</h2>

<div class="jumbotron">

  <p>Username: <%= @user.username %></p>
  <p>E-mail: <%= @user.email %></p>

  <hr>

  <div>
  <h3> Wallet </h3>
  </div>
  <div>
  <p><strong>BTC BALANCE:</strong> <%= @user.default_wallet.btc_total %> BTC</p>
  <p><strong>USD BALANCE:</strong> $<%= @user.default_wallet.usd_total %></p>
  <p><strong>TOTAL PROFIT:</strong> $<%= @user.default_wallet.profits %></p>
  </div>
</div>

<hr>

<div class="jumbotron">
  <div>
    <h3> Trading Console </h3>
  </div>

  <button type="button" class="btn pull-right">
    <%= link_to 'Buy/Sell Coins', new_user_trade_path(@user) %>
  </button>

  <div>
    <h4> Trade History </h4>
  </div>

  <table class="table table-bordered">
    <tr>
      <th>Amount</th>
      <th>Price</th>
      <th>Type</th>
      <th>Total</th>
      <th>Time</th>
    </tr>
    <div>
      <% @trades.each do |trade| %>
        <tr>
        <td><%= trade.amount %> BTC</td>
        <td>$<%= trade.price %></td>
        <td><%= trade.trade_type %></td>
        <td><%= trade.total %> USD</td>
        <td><%= trade.created_at %></td>
        </tr>
      <% end %>
    </div>
  </table>
</div>

<hr>

<div class="jumbotron">
  <h3> Personal Statistics </h3>
  <div>
    <h4> Trades by Day </h4>
    <%= line_chart Trade.group_by_week(:created_at).count %>
  </div>

  <div>
    <h4> Buy/Sell Ratio </h4>
    <%= pie_chart Trade.group(:trade_type).count %>
  </div>
</div>